### PR TITLE
Movie details, create button fix and layout refactor

### PR DESCRIPTION
**Pull request by CLRM1**
## Name
Movie details
## User Task Number
[3](https://github.com/Reuben-Davison/viewing_party_lite/issues/3)
## Branch
movie_details
## Features
Adds two buttons on the user/movie show page (create viewing party and discover page). Adds movie details to new viewing party view. Adds the home button link to each page on the site. Fixes broken link on to register new user on home page.
## Tests
Tests links on user/movie show page and tests API data on create viewing party page.
## Files Created
User movie show, create new viewing party, viewing party controller. 
## Comments
Everything works, but as we discussed, I'm not sure about the initialize method in the facade. If we have time we should look into refactoring if possible/necessary.

### CODE REVIEW

**Review by Reuben-Davison — COMMENTED** [review]
Code is well written and encapsulation is used very well. A couple of things I have noticed:
-Actors are only supposed to display the top 10 actors/actresses. ([:results][0..9] would fix that)
-Reading through the story and it is rather confusing but I feel that the movie info needs to be on the movie detail page and not the create a viewing party page.

**Comment by CLRM1** [comment]
Great catch on these two. You're definitely right about the movie info being on the movie details page. I'll get both fixed.

**Comment by CLRM1** [comment]
Updated.

**Review by Reuben-Davison — APPROVED** [review]
Thanks for making those updates!

**Pull request merged**
